<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>l</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
			  (^%{$)
			| (^.*{\s*$)
	</string>
	<key>foldingStopMarker</key>
	<string>(^%}$)|(^\s*}$)</string>
	<key>name</key>
	<string>Lex Grammar</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>%{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.seperator.lex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=%})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%}</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.seperator.lex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=%%)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.language.optiondef</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.option</string>
						</dict>
					</dict>
					<key>match</key>
					<string>%(option)\s+((no)?(7bit|8bit|align|backup|batch|caseful|c\+\+|case|case|caseless|debug|default|ecs|fast|full|interactive|lex|meta|perf|read|stdout|verbose|warn|array|pointer|input|unput|yy_push_state|yy_pop_state|yy_top_state|yy_scan_buffer|yy_scan_bytes|yy_scan_string|outfile|prefix|yyclass|always\-interactive|main|never\-interactive|stack|stdinit|yylineno|yywrap))</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=%)(x|s)\s+([a-z_A-Z]+)</string>
					<key>name</key>
					<string>keyword.language.xset</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.lexmacro</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.regex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^([a-z_A-Z]+)\s+(.*)$</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%%</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.seperator.lex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>%%</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^((&lt;[a-zA-Z_]+&gt;)?[^\ \t\n]+)?[\t\ ]+[\|\{\}]?</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.regex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.classname</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.classname</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.classname</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;[a-zA-Z_]+&gt;)(,(&lt;[a-zA-Z_]+&gt;))*{</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lex</string>
	<key>uuid</key>
	<string>E8D7E0A1-4B7A-48A7-A222-EFDB74DCD46C</string>
</dict>
</plist>
